/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    activityLog: ActivityLog;
    contatti: Contatti;
    conflittiImport: ConflittiImport;
    inviteCheckRateLimit: InviteCheckRateLimit;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    activityLog: ActivityLogSelect<false> | ActivityLogSelect<true>;
    contatti: ContattiSelect<false> | ContattiSelect<true>;
    conflittiImport: ConflittiImportSelect<false> | ConflittiImportSelect<true>;
    inviteCheckRateLimit: InviteCheckRateLimitSelect<false> | InviteCheckRateLimitSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    hubspotSyncConfig: HubspotSyncConfig;
    apiCredentials: ApiCredential;
    resetContattiELog: ResetContattiELog;
    ticketConfig: TicketConfig;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    hubspotSyncConfig: HubspotSyncConfigSelect<false> | HubspotSyncConfigSelect<true>;
    apiCredentials: ApiCredentialsSelect<false> | ApiCredentialsSelect<true>;
    resetContattiELog: ResetContattiELogSelect<false> | ResetContattiELogSelect<true>;
    ticketConfig: TicketConfigSelect<false> | TicketConfigSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activityLog".
 */
export interface ActivityLog {
  id: string;
  /**
   * Opzionale per sync automatico HubSpot (nessun operatore). Obbligatorio per login/logout/accessDenied.
   */
  user?: (string | null) | User;
  timestamp: string;
  area?: ('admin' | 'app') | null;
  eventType:
    | 'login'
    | 'logout'
    | 'accessDenied'
    | 'hubspotSync'
    | 'csvUpload'
    | 'checkIn'
    | 'wildcardInsert'
    | 'invioTicketWildcard'
    | 'invioTicketResend'
    | 'invioTicketMassivo'
    | 'invioTicketMassivoAvviato'
    | 'invioTicketMassivoCompletato'
    | 'contactsReset';
  /**
   * Applicabile agli invii per-contatto (Wildcard / Resend / massivo). Vuoto sui record di apertura/chiusura processo.
   */
  esito?: ('successo' | 'fallito_email_invalida' | 'fallito_errore_invio' | 'bloccato_modalita_test') | null;
  relatedContact?: (string | null) | Contatti;
  detail?: string | null;
  /**
   * Valori prima della modifica (Caso B) o contesto dello scarto.
   */
  previousValue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Valori applicati (Caso B) o dati riga scartata (Caso C).
   */
  newValue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  method?: ('google' | 'local') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Admin del pannello → Google Login. Utenti App → Google o locale. Il super-admin si crea solo via seed.
   */
  loginMethod?: ('google' | 'local') | null;
  /**
   * Admin: accesso pannello via Google Login. Con accesso locale deve restare Nessuno.
   */
  adminRole: 'none' | 'admin' | 'super-admin';
  /**
   * Accesso all'Area App. Obbligatorio con accesso locale; opzionale se Admin Role = Admin.
   */
  appRole: 'none' | 'hostess' | 'manager' | 'full-access';
  /**
   * Disattivazione senza cancellare il record.
   */
  active?: boolean | null;
  sub?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contatti".
 */
export interface Contatti {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Opzionale. Unique con indice sparse se assente (fase-4-import-sync.md §2.1).
   */
  email?: string | null;
  dudeCompany?: string | null;
  category?:
    | (
        | 'Clients'
        | 'Prospects'
        | 'Supplier'
        | 'Talent'
        | 'Partner'
        | 'Founders'
        | 'Design'
        | 'Local Community'
        | 'Friend'
        | 'exDude'
        | 'Event Guest'
        | 'Needs Review'
      )
    | null;
  assegnazione?: string | null;
  /**
   * UUID v4 generato all’inserimento/aggiornamento se assente (hook Contatti). Unique, immutabile salvo rigenerazione manuale esplicita.
   */
  qrToken?: string | null;
  /**
   * Modalità effettivamente usata per il QR di questo contatto. Default da ticketConfig se assente alla prima generazione.
   */
  qrContentMode?: ('token' | 'fullData') | null;
  /**
   * Timestamp dell’ultimo invio email ticket riuscito (qualunque canale). Vuoto = mai inviato via email.
   */
  ticketInviatoAt?: string | null;
  checkIn?: boolean | null;
  checkInAt?: string | null;
  checkInBy?: (string | null) | User;
  /**
   * Valore copiato da HubSpot as-is, nessun collegamento a users.
   */
  hubspotOwner?: string | null;
  hubspotRecordId?: string | null;
  /**
   * Copia da HubSpot (party_dude) — verifica manuale del segmento sync.
   */
  partyDude?: string | null;
  /**
   * Copia da HubSpot (party_ttt) — verifica manuale del segmento sync.
   */
  partyTtt?: string | null;
  /**
   * Fonte di creazione originale del record — non aggiornata da sync di precedenza (Caso B).
   */
  source?: ('Hubspot' | 'Upload' | 'Wildcard') | null;
  /**
   * "Hubspot", "CSV" o username del manager (Wildcard).
   */
  createdBy?: string | null;
  /**
   * Soft delete: false = uscito dal segmento o disattivato (Caso F).
   */
  attivo?: boolean | null;
  /**
   * Flag rapido per contatti con voce aperta in conflittiImport.
   */
  hasOpenConflict?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conflittiImport".
 */
export interface ConflittiImport {
  id: string;
  contatto: string | Contatti;
  source: 'csv' | 'hubspot';
  /**
   * Snapshot dei valori della riga/record in conflitto (Caso D, fase-4-import-sync.md §2.2).
   */
  datiIncoming?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  note?: string | null;
  stato: 'aperto' | 'risolto';
  risoltoDa?: (string | null) | User;
  risoltoIl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inviteCheckRateLimit".
 */
export interface InviteCheckRateLimit {
  id: string;
  ip: string;
  timestamp: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'activityLog';
        value: string | ActivityLog;
      } | null)
    | ({
        relationTo: 'contatti';
        value: string | Contatti;
      } | null)
    | ({
        relationTo: 'conflittiImport';
        value: string | ConflittiImport;
      } | null)
    | ({
        relationTo: 'inviteCheckRateLimit';
        value: string | InviteCheckRateLimit;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activityLog_select".
 */
export interface ActivityLogSelect<T extends boolean = true> {
  user?: T;
  timestamp?: T;
  area?: T;
  eventType?: T;
  esito?: T;
  relatedContact?: T;
  detail?: T;
  previousValue?: T;
  newValue?: T;
  method?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contatti_select".
 */
export interface ContattiSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  dudeCompany?: T;
  category?: T;
  assegnazione?: T;
  qrToken?: T;
  qrContentMode?: T;
  ticketInviatoAt?: T;
  checkIn?: T;
  checkInAt?: T;
  checkInBy?: T;
  hubspotOwner?: T;
  hubspotRecordId?: T;
  partyDude?: T;
  partyTtt?: T;
  source?: T;
  createdBy?: T;
  attivo?: T;
  hasOpenConflict?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conflittiImport_select".
 */
export interface ConflittiImportSelect<T extends boolean = true> {
  contatto?: T;
  source?: T;
  datiIncoming?: T;
  note?: T;
  stato?: T;
  risoltoDa?: T;
  risoltoIl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inviteCheckRateLimit_select".
 */
export interface InviteCheckRateLimitSelect<T extends boolean = true> {
  ip?: T;
  timestamp?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  loginMethod?: T;
  adminRole?: T;
  appRole?: T;
  active?: T;
  sub?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  /**
   * Allow-list domini per login Google. Almeno un dominio obbligatorio.
   */
  authorizedDomains?:
    | {
        domain: string;
        allowAdmin?: boolean | null;
        allowApp?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hubspotSyncConfig".
 */
export interface HubspotSyncConfig {
  id: string;
  /**
   * Nome interno della proprietà HubSpot (es. party_dude, party_ttt). Testo libero, non un elenco fisso.
   */
  proprietaFiltro?: string | null;
  /**
   * Valore che qualifica il contatto per il sync (es. SI, YES).
   */
  valoreInclusione?: string | null;
  syncAutomatico?: boolean | null;
  /**
   * Obbligatorio se il sync automatico è attivo.
   */
  intervalloMinuti?: number | null;
  /**
   * Lock applicativo — gestito dal codice di sync (Passo 3).
   */
  syncInProgress?: boolean | null;
  /**
   * Timestamp di avvio sync — per riconoscere un lock morto (Passo 3).
   */
  syncStartedAt?: string | null;
  /**
   * Avanzamento sync — gestito dal codice, non modificare manualmente.
   */
  syncProgressPages?: number | null;
  /**
   * Contatti già processati nel sync in corso.
   */
  syncProgressProcessed?: number | null;
  /**
   * Totale contatti nel segmento HubSpot (dalla prima risposta API).
   */
  syncProgressTotal?: number | null;
  /**
   * importazione | riconciliazione
   */
  syncProgressPhase?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apiCredentials".
 */
export interface ApiCredential {
  id: string;
  /**
   * Chiavi Bearer per consumer esterni (es. landing page). Mostra, copia e ruota come le Service Key HubSpot.
   */
  chiavi?:
    | {
        /**
         * Nome descrittivo del consumer (es. Landing page Firebase).
         */
        etichetta: string;
        /**
         * Primi caratteri visibili (non sensibili — il resto è cifrato).
         */
        keyPrefix?: string | null;
        chiaveCifrata?: string | null;
        attiva?: boolean | null;
        creataIl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resetContattiELog".
 */
export interface ResetContattiELog {
  id: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticketConfig".
 */
export interface TicketConfig {
  id: string;
  /**
   * Testo mostrato sul biglietto (email e pagina pubblica).
   */
  locationEvento?: string | null;
  /**
   * Valore applicato ai nuovi contatti (e al backfill) se qrContentMode non è ancora valorizzato.
   */
  qrContentModeDefault?: ('token' | 'fullData') | null;
  /**
   * Attivare dopo l’upgrade del piano Resend a Pro, prima di eseguire l’invio massivo. Non riguarda gli invii singoli (Wildcard/resend).
   */
  pianoResendPro?: boolean | null;
  /**
   * Se attiva, le email ticket partono solo verso gli indirizzi in Contatti di test. Default: attiva (sistema protetto). Disattivare solo quando si è pronti a comunicare con invitati reali.
   */
  modalitaTestInvio?: boolean | null;
  /**
   * Whitelist usata solo con Modalità test invio attiva. Inserire esclusivamente indirizzi di test del team — mai email di invitati reali. Se la lista è vuota e la modalità test è attiva, nessuna email parte.
   */
  contattiTest?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lock applicativo — gestito dal codice di invio massivo (Passo 6+).
   */
  invioTicketInProgress?: boolean | null;
  /**
   * Timestamp di avvio — per riconoscere un lock morto (stessa soglia del sync HubSpot).
   */
  invioTicketStartedAt?: string | null;
  /**
   * Avanzamento invio massivo — gestito dal codice.
   */
  invioTicketProgressProcessed?: number | null;
  /**
   * Totale contatti nel perimetro dell’invio in corso.
   */
  invioTicketProgressTotal?: number | null;
  /**
   * Fase testuale dell’invio massivo (es. invio | report).
   */
  invioTicketProgressPhase?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  authorizedDomains?:
    | T
    | {
        domain?: T;
        allowAdmin?: T;
        allowApp?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hubspotSyncConfig_select".
 */
export interface HubspotSyncConfigSelect<T extends boolean = true> {
  proprietaFiltro?: T;
  valoreInclusione?: T;
  syncAutomatico?: T;
  intervalloMinuti?: T;
  syncInProgress?: T;
  syncStartedAt?: T;
  syncProgressPages?: T;
  syncProgressProcessed?: T;
  syncProgressTotal?: T;
  syncProgressPhase?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apiCredentials_select".
 */
export interface ApiCredentialsSelect<T extends boolean = true> {
  chiavi?:
    | T
    | {
        etichetta?: T;
        keyPrefix?: T;
        chiaveCifrata?: T;
        attiva?: T;
        creataIl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resetContattiELog_select".
 */
export interface ResetContattiELogSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticketConfig_select".
 */
export interface TicketConfigSelect<T extends boolean = true> {
  locationEvento?: T;
  qrContentModeDefault?: T;
  pianoResendPro?: T;
  modalitaTestInvio?: T;
  contattiTest?:
    | T
    | {
        email?: T;
        id?: T;
      };
  invioTicketInProgress?: T;
  invioTicketStartedAt?: T;
  invioTicketProgressProcessed?: T;
  invioTicketProgressTotal?: T;
  invioTicketProgressPhase?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}